#! /bin/bash
# P1: me 
# ./resources/filler_vm -p1 ./mchuang.filler -p2 resources/players/hcao.filler -v -f resources/maps/map${1}

# P2: me
./resources/filler_vm -p2 ./mchuang.filler -p1 resources/players/hcao.filler -v -f resources/maps/map${1}

# Only me
# ./resources/filler_vm -p1 ./mchuang.filler -v -f resources/maps/map${1}





# $$$ exec p1 : [./mchuang.filler]
# Plateau 15 10 :
#     01234567890123456
# 000 .................
# 001 .................
# 002 .................
# 003 .................
# 004 .................
# 005 .................
# 006 .................
# 007 .................
# 008 ..O..............
# 009 .................
# 010 .................
# 011 .................
# 012 ..............X..
# 013 .................
# 014 .................
# Piece 1 2:
# **